name: Release
on:
  push:
    branches: [main]
    paths-ignore: [".github/**"]

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: burritocatai/cat-go-release-action/.github/workflows/release.yml@main
    with:
      binary-name: gitcat
    secrets: inherit
